### ISSUE TITLE
NTR: Request for S13 bloom

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S13#3]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>bloom <p><b>Definition</b><p> Term to be used when the property reported is said to be the characteristic of a bloom. An algal bloom is defined as a rapid increase and accumulation of algal biomass in water bodies including, for macroalgal blooms, intertidal areas. For more information see:  https://en.wikipedia.org/wiki/Algal_bloom<p><H2> Optional </H2><p><b>Sources/references</b><p> https://en.wikipedia.org/wiki/Algal_bloom; https://github.com/nvs-vocabs/P01/issues/190<p> <b>Mapping to other terminologies </b><p> http://www.eionet.europa.eu/gemet/concept/303; http://purl.obolibrary.org/obo/ENVO_2000004<p>

**Comment by gwemon** [comment]
Live on the NVS: http://vocab.nerc.ac.uk/collection/S13/current/S1366/
