### ISSUE TITLE
NTR: Request for S13 stranding

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S13#4]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>stranding <p><b>Definition</b><p> Term to be used when the property reported is said to be the characteristic of a stranding. The term applies to marine organisms (animals or seaweeds) found washed up on the shore in a dead, dying or abnormal state. <p><H2> Optional </H2><p><b>Sources/references</b><p> https://github.com/nvs-vocabs/P01/issues/190<p>

**Comment by gwemon** [comment]
Live on the NVS: http://vocab.nerc.ac.uk/collection/S13/current/S1367/
