### ISSUE TITLE
NTR: Request for S13 non-colonial

### ISSUE THREAD

**Issue by nvsvocabs** [nvs-vocabs/S13#6]
<H2> Required </H2><p><b>Term name (PrefLabel)</b><p>non-colonial <p><b>Definition</b><p> organisms which are solitary and do not form part of a colony<p><H2> Optional </H2><p>

**Comment by jakjonbodc** [comment]
https://github.com/nvs-vocabs/P01/issues/209

**Comment by gwemon** [comment]
Would prefer the definition to be: "The observed biological entity is of a non-colonial type."

**Comment by jakjonbodc** [comment]
S13 term created for non-colonial - S1370

**Comment by jakjonbodc** [comment]
http://vocab.nerc.ac.uk/collection/S13/current/S1370/
