### ISSUE TITLE
NTR: penis-bearing females

### ISSUE THREAD

**Issue by gwemon** [nvs-vocabs/S13#7]
To be used in P01 code for Proportion of Nucella lapillus penis bearing females. In relation to: https://github.com/https://github.com/nvs-vocabs/P01/issues/214

**Comment by roswri** [comment]
suggested description: 
A term describing organisms affected by imposex, a condition resulting in the development of a penis and vas deferens in female gastropods when exposed to certain pollutants.

**Comment by gwemon** [comment]
@roswri  Good definition but now I am hesitating whether S13 is the right vocab for this! Shall we discuss it on Monday if you haven't created it already?

**Comment by roswri** [comment]
@gwemon, happy to discuss on Monday, I hesitated in creating it because I also wasn't sure this was the right vocab! I thinks it's also worth considering S10 since it's sex related, or S14 since it's a morphological phenomenon.

**Comment by roswri** [comment]
Decision made that S13 is the correct vocab for this term, because the gender of the organism would still be female, this new S13 term would just allow sub-grouping of the females affected by imposex

**Comment by roswri** [comment]
Term queued for publication: S1371 - penis-bearing females

**Comment by roswri** [comment]
Term live on NVS:
http://vocab.nerc.ac.uk/collection/S13/current/S1371/
